package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// verbGroup renders verbs as a regex alternation, e.g. "(delete)".
func verbGroup(verbs []string) string {
	return "(" + strings.Join(verbs, "|") + ")"
}

// --- Claude Code ---

func emitClaudeCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctVerbs(g.asked())

	deny := []string{}
	for _, v := range blocked {
		deny = append(deny, fmt.Sprintf("Bash(%s * %s:*)", guardBinary, v))
	}
	if len(blocked) > 0 {
		deny = append(deny, "mcp__.*"+guardMCPPrefix+".*_"+verbGroup(blocked))
	}
	ask := []string{}
	for _, v := range asked {
		ask = append(ask, fmt.Sprintf("Bash(%s * %s:*)", guardBinary, v))
	}
	if len(asked) > 0 {
		ask = append(ask, "mcp__.*"+guardMCPPrefix+".*_"+verbGroup(asked))
	}

	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/n8nctl-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{"deny": deny, "ask": ask},
		"hooks": map[string]any{
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__.*" + guardMCPPrefix + ".*")},
		},
	}
	settingsJSON, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Claude Code agent-safety config. The MCP-tool branch of the hook is a hard")
	fmt.Fprintln(out, "# block (structured tool names can't be obfuscated); the Bash branch is")
	fmt.Fprintln(out, "# best-effort — it defeats quote/backslash tricks but not variable")
	fmt.Fprintln(out, "# indirection or shell aliases, so MCP-only operation (or a read-only")
	fmt.Fprintln(out, "# sandbox) is the strongest guarantee. The permission rules are")
	fmt.Fprintln(out, "# belt-and-suspenders. Regenerate after upgrading n8nctl.")
	fmt.Fprintln(out)
	if err := writeOrPrint(cmd, write, claudeHookPath(), claudeHookScript(blocked), 0o755); err != nil { //nolint:gosec // executable hook
		return err
	}
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, claudeSettingsPath(), string(settingsJSON)+"\n", 0o644)
}

func claudeHookPath() string     { return filepath.Join(".claude", "hooks", "n8nctl-guard.sh") }
func claudeSettingsPath() string { return filepath.Join(".claude", "settings.json") }

func claudeHookScript(blocked []string) string {
	return `#!/usr/bin/env bash
# n8nctl agent guard — blocks irreversible n8n operations on the Bash and MCP
# surfaces. Generated by ` + "`n8nctl agent guard`" + `; regenerate after
# upgrading n8nctl so new actions are covered.
#
# The MCP-tool branch is a hard block. The Bash branch is best-effort: it defeats
# quote/backslash obfuscation but NOT variable indirection or shell aliases — run
# agents MCP-only or in a read-only sandbox for a hard guarantee.
verbs='` + verbGroup(blocked) + `'
input=$(cat)

deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# Without jq we cannot isolate the tool name. Fail safe, not open: scan the raw
# payload for an irreversible n8nctl verb and deny if present.
if ! command -v jq >/dev/null 2>&1; then
  if printf '%s' "$input" | tr '\n' ' ' | grep -qiE "` + guardBinary + `.*${verbs}"; then
    deny_raw "n8nctl agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

deny() {
  jq -c -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    # Strip quotes/backslashes (\042=" \047=' \134=\) to defeat trivial
    # obfuscation, and flatten newlines so a split verb can't slip past grep.
    stripped=$(printf '%s' "$cmd" | tr -d '\042\047\134')
    if printf '%s\n%s' "$cmd" "$stripped" | tr '\n' ' ' | grep -qiE "\b` + guardBinary + `\b.*\b${verbs}\b"; then
      deny "n8nctl agent guard: irreversible operation blocked (${verbs})."
    fi
    ;;
  mcp__*` + guardMCPPrefix + `*)
    if printf '%s' "$tool" | grep -qiE "_${verbs}$"; then
      deny "n8nctl agent guard: irreversible MCP tool blocked (${tool})."
    fi
    ;;
esac
exit 0
`
}

// --- Codex ---

func emitCodex(cmd *cobra.Command, g guardPlan, write bool) error {
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Codex agent-safety config (~/.codex/config.toml).")
	fmt.Fprintln(out, "# Codex has no per-command deny hook: read-only sandbox is the hard block,")
	fmt.Fprintln(out, "# and destructive MCP tools (which n8nctl annotates) already require approval.")
	fmt.Fprintln(out)
	mode := "read-only"
	policy := "untrusted"
	note := "# read-only sandbox: no n8nctl write can run without an explicit approval."
	if !g.allWrites {
		note = "# read-only sandbox + untrusted: writes pause for approval; reads run free.\n" +
			"# Switch sandbox_mode to \"workspace-write\" only if you accept unattended writes."
	}
	content := fmt.Sprintf("sandbox_mode    = %q\napproval_policy = %q\n\n%s\n", mode, policy, note)
	return writeOrPrint(cmd, write, codexConfigPath(write), content, 0o644)
}

func codexConfigPath(write bool) string {
	if write {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".codex", "config.toml")
		}
	}
	return "~/.codex/config.toml"
}

// --- OpenCode ---

func emitOpenCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctVerbs(g.asked())

	bash := map[string]any{"*": "allow"}
	perm := map[string]any{}
	for _, v := range blocked {
		bash[guardBinary+" * "+v+"*"] = "deny"
		perm[guardMCPPrefix+"_*_"+v] = "deny"
	}
	for _, v := range asked {
		bash[guardBinary+" * "+v+"*"] = "ask"
		perm[guardMCPPrefix+"_*_"+v] = "ask"
	}
	perm["bash"] = bash

	cfg := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perm,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# OpenCode agent-safety config (opencode.json). `deny` is a hard block;")
	fmt.Fprintln(out, "# `ask` prompts. The specific n8nctl patterns take precedence over the `*`")
	fmt.Fprintln(out, "# catch-all, which allows everything else.")
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, "opencode.json", string(b)+"\n", 0o644)
}
