package wflint

import (
	_ "embed"
	"encoding/json"
	"sort"
	"strings"
	"sync"
)

// node_catalog.json is generated by tools/gen-node-schemas from n8n's published
// node descriptions. It maps each node type to its display name and valid
// parameter names, and powers the unknown-node-type / unknown-parameter rules.
//
//go:embed node_catalog.json
var catalogJSON []byte

// knownNodePrefixes are the packages the catalog covers. Types outside these
// prefixes (community / custom nodes) are never flagged as unknown — we have no
// schema for them, so flagging them would be a false positive.
var knownNodePrefixes = []string{"n8n-nodes-base.", "@n8n/n8n-nodes-langchain."}

type catalogEntry struct {
	DisplayName string   `json:"displayName"`
	Params      []string `json:"params"`
}

type nodeCatalog struct {
	versions map[string]string
	types    []string                   // sorted type names, for suggestions
	params   map[string]map[string]bool // type -> set of valid parameter names
	display  map[string]string          // type -> display name
}

// NodeInfo is a public view of one catalogued node type, for the `nodes` command.
type NodeInfo struct {
	Type        string   `json:"type"`
	DisplayName string   `json:"displayName"`
	Params      []string `json:"params"`
}

var (
	catalogOnce sync.Once
	catalog     nodeCatalog
)

func loadCatalog() *nodeCatalog {
	catalogOnce.Do(func() {
		var raw struct {
			GeneratedFrom map[string]string       `json:"generatedFrom"`
			Nodes         map[string]catalogEntry `json:"nodes"`
		}
		_ = json.Unmarshal(catalogJSON, &raw)
		catalog.versions = raw.GeneratedFrom
		catalog.params = make(map[string]map[string]bool, len(raw.Nodes))
		catalog.display = make(map[string]string, len(raw.Nodes))
		catalog.types = make([]string, 0, len(raw.Nodes))
		for t, e := range raw.Nodes {
			set := make(map[string]bool, len(e.Params))
			for _, p := range e.Params {
				set[p] = true
			}
			catalog.params[t] = set
			catalog.display[t] = e.DisplayName
			catalog.types = append(catalog.types, t)
		}
		sort.Strings(catalog.types)
	})
	return &catalog
}

// Nodes returns every catalogued node type, sorted by type. Used by `n8nctl nodes`.
func Nodes() []NodeInfo {
	c := loadCatalog()
	out := make([]NodeInfo, 0, len(c.types))
	for _, t := range c.types {
		out = append(out, nodeInfo(c, t))
	}
	return out
}

// Node returns one node's info, if catalogued.
func Node(nodeType string) (NodeInfo, bool) {
	c := loadCatalog()
	if _, ok := c.params[nodeType]; !ok {
		return NodeInfo{}, false
	}
	return nodeInfo(c, nodeType), true
}

// SuggestNodeType returns the closest known type to a (likely mistyped) one.
func SuggestNodeType(nodeType string) (string, bool) { return suggestNode(nodeType) }

// NodeTypeCorrection returns a corrected node type when nodeType is from a known
// package, is not in the catalog, and has a close match — i.e. a fixable typo.
func NodeTypeCorrection(nodeType string) (string, bool) {
	if hasKnownPrefix(nodeType) && !nodeKnown(nodeType) {
		return suggestNode(nodeType)
	}
	return "", false
}

// CatalogBasis exposes the catalog provenance string.
func CatalogBasis() string { return catalogBasis() }

func nodeInfo(c *nodeCatalog, t string) NodeInfo {
	params := make([]string, 0, len(c.params[t]))
	for p := range c.params[t] {
		params = append(params, p)
	}
	sort.Strings(params)
	return NodeInfo{Type: t, DisplayName: c.display[t], Params: params}
}

// catalogBasis describes the catalog provenance for the rule listing.
func catalogBasis() string {
	c := loadCatalog()
	parts := make([]string, 0, len(c.versions))
	for pkg, ver := range c.versions {
		parts = append(parts, pkg+"@"+ver)
	}
	sort.Strings(parts)
	return "n8n node catalog (" + strings.Join(parts, ", ") + ")"
}

// hasKnownPrefix reports whether a node type belongs to a package the catalog
// covers (so absence from the catalog is meaningful, not just unknown coverage).
func hasKnownPrefix(nodeType string) bool {
	for _, p := range knownNodePrefixes {
		if strings.HasPrefix(nodeType, p) {
			return true
		}
	}
	return false
}

func nodeKnown(nodeType string) bool {
	_, ok := loadCatalog().params[nodeType]
	return ok
}

func paramKnown(nodeType, param string) bool {
	set, ok := loadCatalog().params[nodeType]
	if !ok {
		return true // unknown node — don't second-guess its params
	}
	return set[param]
}

// suggestNode returns the closest known type (same prefix) within edit distance 2.
func suggestNode(nodeType string) (string, bool) {
	c := loadCatalog()
	best, bestDist := "", 3
	for _, t := range c.types {
		if !samePrefix(t, nodeType) {
			continue
		}
		if d := levenshtein(t, nodeType); d < bestDist {
			best, bestDist = t, d
		}
	}
	return best, best != ""
}

// suggestParam returns the closest valid parameter name within edit distance 2.
func suggestParam(nodeType, param string) (string, bool) {
	set, ok := loadCatalog().params[nodeType]
	if !ok {
		return "", false
	}
	best, bestDist := "", 3
	for p := range set {
		if d := levenshtein(strings.ToLower(p), strings.ToLower(param)); d < bestDist {
			best, bestDist = p, d
		}
	}
	return best, best != ""
}

func samePrefix(a, b string) bool {
	for _, p := range knownNodePrefixes {
		if strings.HasPrefix(a, p) && strings.HasPrefix(b, p) {
			return true
		}
	}
	return false
}

// levenshtein is the standard edit distance, used for "did you mean" suggestions.
func levenshtein(a, b string) int {
	la, lb := len(a), len(b)
	if la == 0 {
		return lb
	}
	if lb == 0 {
		return la
	}
	prev := make([]int, lb+1)
	for j := 0; j <= lb; j++ {
		prev[j] = j
	}
	for i := 1; i <= la; i++ {
		cur := make([]int, lb+1)
		cur[0] = i
		for j := 1; j <= lb; j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			cur[j] = min(cur[j-1]+1, prev[j]+1, prev[j-1]+cost)
		}
		prev = cur
	}
	return prev[lb]
}
